### ISSUE TITLE
ImportError: cannot import name '_app_ctx_stack' from 'flask'

### ISSUE THREAD

**Issue by Fernien** [olqs/mailcow-traefik-cert-helper#1]
Hi,
since your last push ~ 2 weeks ago i get this error inside the container which lets him crash and not generate any certificates.
docker compose logs -f mailcow-traefik-cert-helper

#docker compose logs -f mailcow-traefik-cert-helper
```
mailcowdockerized_mailcow-traefik-cert-helper  | Usage: python -m flask run [OPTIONS]
mailcowdockerized_mailcow-traefik-cert-helper  | Try 'python -m flask run --help' for help.
mailcowdockerized_mailcow-traefik-cert-helper  |
mailcowdockerized_mailcow-traefik-cert-helper  | Error: While importing 'app', an ImportError was raised:
mailcowdockerized_mailcow-traefik-cert-helper  |
mailcowdockerized_mailcow-traefik-cert-helper  | Traceback (most recent call last):
mailcowdockerized_mailcow-traefik-cert-helper  |   File "/usr/local/lib/python3.12/site-packages/flaskext/mysql.py", line 5, in <module>
mailcowdockerized_mailcow-traefik-cert-helper  |     from flask import _app_ctx_stack as _ctx_stack
mailcowdockerized_mailcow-traefik-cert-helper  | ImportError: cannot import name '_app_ctx_stack' from 'flask' (/usr/local/lib/python3.12/site-packages/flask/__init__.py)
mailcowdockerized_mailcow-traefik-cert-helper  |
mailcowdockerized_mailcow-traefik-cert-helper  | During handling of the above exception, another exception occurred:
mailcowdockerized_mailcow-traefik-cert-helper  |
mailcowdockerized_mailcow-traefik-cert-helper  | Traceback (most recent call last):
mailcowdockerized_mailcow-traefik-cert-helper  |   File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 219, in locate_app
mailcowdockerized_mailcow-traefik-cert-helper  |     __import__(module_name)
mailcowdockerized_mailcow-traefik-cert-helper  |   File "/app/app.py", line 2, in <module>
mailcowdockerized_mailcow-traefik-cert-helper  |     from flaskext.mysql import MySQL
mailcowdockerized_mailcow-traefik-cert-helper  |   File "/usr/local/lib/python3.12/site-packages/flaskext/mysql.py", line 7, in <module>
mailcowdockerized_mailcow-traefik-cert-helper  |     from flask import _request_ctx_stack as _ctx_stack
```

Can you fix it?

**Comment by olqs-org** [comment]
Hi,
thanks for the issue, i have pulled the changes in your fork.
Flask-MySQLdb needs different app config properties.
I have fixed this, rebuild and pushed the container.
